//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_MNLG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TS_NMLGANG_DBEntities1 : DbContext
    {
        public TS_NMLGANG_DBEntities1()
            : base("name=TS_NMLGANG_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CA_TABLE> CA_TABLE { get; set; }
        public virtual DbSet<LOCAO_TABLE> LOCAO_TABLE { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<NMLGANGTABLE_THONGSOHOAHOCME> NMLGANGTABLE_THONGSOHOAHOCME { get; set; }
        public virtual DbSet<NMLGANGTABLE_THONGSOME> NMLGANGTABLE_THONGSOME { get; set; }
        public virtual DbSet<NMLGANGTABLE_THONGSOVATLYME> NMLGANGTABLE_THONGSOVATLYME { get; set; }
    }
}
