//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_MNLG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NMLGANGTABLE_THONGSOVATLYME
    {
        public int IDVL { get; set; }
        public Nullable<int> thoiGianRaGang { get; set; }
        public Nullable<int> gianCach { get; set; }
        public Nullable<int> thoiGianRaXi { get; set; }
        public Nullable<double> tiLeTGGangXi { get; set; }
        public Nullable<double> doSauLoGang { get; set; }
        public Nullable<double> luongBunBit { get; set; }
        public Nullable<double> sanLuong { get; set; }
        public Nullable<double> nhietDoGang { get; set; }
        public Nullable<double> khoiLuong { get; set; }
        public Nullable<int> loaiGang { get; set; }
    }
}
