//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_MNLG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NMLGANGTABLE_THONGSOME
    {
        public int IDM { get; set; }
        public Nullable<System.DateTime> thoiGian { get; set; }
        public Nullable<int> caID { get; set; }
        public Nullable<int> meGang { get; set; }
        public Nullable<int> soThung { get; set; }
        public Nullable<int> sanRaGang { get; set; }
    }
}
