//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_MNLG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NMLGANGTABLE_THONGSOHOAHOCME
    {
        public int IDHH { get; set; }
        public Nullable<double> TPHH_C { get; set; }
        public Nullable<double> TPHH_Si { get; set; }
        public Nullable<double> TPHH_Mn { get; set; }
        public Nullable<double> TPHH_S { get; set; }
        public Nullable<double> TPHH_P { get; set; }
        public Nullable<double> TPHH_Ti { get; set; }
        public Nullable<double> TPHH_SiO2 { get; set; }
        public Nullable<double> TPHH_Al2O3 { get; set; }
        public Nullable<double> TPHH_CaO { get; set; }
        public Nullable<double> TPHH_MgO { get; set; }
        public Nullable<double> TPHH_TiO2 { get; set; }
        public Nullable<double> TPHH_Ri { get; set; }
    }
}
